apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
  - name: output

  params:
  - name: args
    default: -v

  steps:
  - name: nosetests
    image: python:3.9-slim
    workingDir: $(workspaces.output.path)
    script: |
      set -e

      echo "WORKDIR CHECK:"
      pwd
      ls -la

      echo "LOOKING FOR REQUIREMENTS:"
      find . -name requirements.txt

      python -m pip install --upgrade pip wheel

      pip install -r requirements.txt

      nosetests $(params.args)