apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: new-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: app-name
      type: string
    - name: build-image
      type: string

  workspaces:
    - name: source

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: output
          workspace: source

    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: source
      runAfter: ["cleanup"]

    - name: flake8
      taskRef:
        name: flake8
      workspaces:
        - name: output
          workspace: source
      runAfter: ["git-clone"]

    - name: nose
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: source
      runAfter: ["flake8"]

    - name: buildah
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: $(params.build-image)
      workspaces:
        - name: output
          workspace: source
      runAfter: ["nose"]

    - name: deploy
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) \
            --image=$(params.build-image) \
            --dry-run=client -o yaml | oc apply -f -
      runAfter: ["buildah"]

      